Add CI/CD Release Tools subsection to Resources & figcd to it
figma/plugin-resources pull request #44
Opened 2023-10-05 22:17 UTC by acohen31

Resolves #40

2023-10-06 04:58 UTC, akbarbmirza requested changes
this looks great - just need to adjust the TOC link location. Once that's fixed, I'll merge it.

2023-10-06 04:58 UTC, akbarbmirza commented on README.md
> +**[⬆ Back to TOC](#table-of-contents)**
This Back to TOC should be below the figcd entry. Fix that and it'll be good to merge.

2023-10-06 14:40 UTC, acohen31 commented
I made the change and added a subsection hook for the CI/CD Release Tools under the resource section. Let me know if there is anything else!

2023-10-06 14:52 UTC, akbarbmirza approved these changes
LGTM

2023-10-06 14:52 UTC, merged

2023-10-24 20:36 UTC, akbarbmirza commented on README.md
> +[SOURCE CODE](https://github.com/parrot-global/figcd) · [MIT](https://github.com/evilmartians/figma-polychrom/blob/main/LICENSE)
Hey @acohen31 - I just realized that the license URL used here is wrong. Can you please fix this?

2023-10-25 13:27 UTC, acohen31 commented on README.md
> +[SOURCE CODE](https://github.com/parrot-global/figcd) · [MIT](https://github.com/evilmartians/figma-polychrom/blob/main/LICENSE)
Sure I'll get this done