Added Include plugin to readme
figma/plugin-resources pull request #54
Opened 2023-11-02 21:11 UTC by mkbhuiyan96

This resolves #52

2023-11-03 20:01 UTC, akbarbmirza requested changes
Add the missing newline and remove the Back to TOC bookmark and this is ready to be merged.

2023-11-03 20:01 UTC, akbarbmirza commented on README.md
> +**[⬆ Back to TOC](#table-of-contents)**
This bookmark back to TOC doesn't belong in this commit. There are a few more entries in this section. There is a bookmark at the end of the section. Please remove this and the extra newline.

2023-11-06 21:06 UTC, akbarbmirza approved these changes

2023-11-06 21:06 UTC, merged

2023-11-07 20:55 UTC, akbarbmirza commented
hey @mkbhuiyan96 do you have a LinkedIn and Twitter? Would love to shout you out!

2023-11-07 21:07 UTC, mkbhuiyan96 commented
Hi @akbarbmirza I don't have Twitter but here's [my LinkedIn.](https://www.linkedin.com/in/mohammad-bhuiyan-a5aa91242/) Thanks!